name: Config Import

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Run import
        run: /usr/local/bin/import
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
